### ISSUE TITLE
Example with ES6 imports

### ISSUE THREAD

**Issue by prateekjadhwani** [pimterry/server-components#25]
I was wondering if there is a way to create a component in ES6 syntax and import it into another components. Would it be possible for you to modify the attached examples in the `README` file?

**Comment by pimterry** [comment]
What do you mean by 'ES6' syntax? Some options:
- Using ES6 features like arrow functions. Yes, definitely - you can use whatever your version of node supports, and it will Just Work.
- Using ES6 modules for import/export. No, not without a transpiler back to CommonJS, since (afaik) Node doesn't have any support for these yet.

**Comment by pimterry** [comment]
Ah, you've actually specified in it the title - imports/exports.

No: server components doesn't have built-in support for that, so you'll need external support, and Node doesn't do that yet. I think the latest details on Node's plan for this are at https://github.com/nodejs/node-eps/blob/master/002-es6-modules.md, and the tracking issue is https://github.com/nodejs/help/issues/53. Alternatively, you can use [Babel](https://babeljs.io) for this in the meantime.

If I were you though, I wouldn't worry about it for now - you don't gain much vs CommonJS, and support doesn't really exist for them anywhere yet.
