### ISSUE TITLE
Is this project abandoned?

### ISSUE THREAD

**Issue by prateekjadhwani** [pimterry/server-components#29]
Hi @pimterry 

Is this project **abandoned**? I was planning to use it somewhere.
Just wondering since the _last commit was in June, 2016_

Thanks

**Comment by pimterry** [comment]
It's definitely not, it's just it's a small library and there hasn't been much need for changes recently (and June wasn't that long ago, to be fair).

This is fairly experimental though, which might be a concern. As a proof of concept it works really nicely, and the model is really interesting, but you should be aware that there's likely to be breaking API changes (e.g. the move to custom elements v1), simply because the underlying standards we're looking at have been still in flux too.

**Comment by prateekjadhwani** [comment]
Thanks for letting me know.
